# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~1.15.18"

[[constraint]]
  name = "github.com/docker/docker"
  version = "~1.13.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.24.0"

[[constraint]]
  branch = "master"
  name = "github.com/mholt/archiver"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/termie/go-shutil"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "~1.19.1"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.7.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  name = "github.com/ericchiang/k8s"
  version = "1.2.0"

[[constraint]]
  branch = "v2"
  name = "github.com/go-validator/validator"
